// Copyright 2026 mbulling83. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type Bootstrap struct {
	Chips json.RawMessage `json:"chips"`
	ElementStats json.RawMessage `json:"element_stats"`
	ElementTypes json.RawMessage `json:"element_types"`
	Elements json.RawMessage `json:"elements"`
	Events json.RawMessage `json:"events"`
	GameSettings json.RawMessage `json:"game_settings"`
	Phases json.RawMessage `json:"phases"`
	Teams json.RawMessage `json:"teams"`
	TotalPlayers int `json:"total_players"`
}

type ClassicLeague struct {
	League json.RawMessage `json:"league"`
	NewEntries json.RawMessage `json:"new_entries"`
	Standings json.RawMessage `json:"standings"`
}

type ClassicLeagueEntry struct {
	Entry int `json:"entry"`
	EntryName string `json:"entry_name"`
	EventTotal int `json:"event_total"`
	Id int `json:"id"`
	LastRank int `json:"last_rank"`
	PlayerName string `json:"player_name"`
	Rank int `json:"rank"`
	RankSort int `json:"rank_sort"`
	Total int `json:"total"`
}

type DreamTeam struct {
	Team json.RawMessage `json:"team"`
	TopPlayer json.RawMessage `json:"top_player"`
}

type Element struct {
	Assists int `json:"assists"`
	Bonus int `json:"bonus"`
	Bps int `json:"bps"`
	ChanceOfPlayingNextRound int `json:"chance_of_playing_next_round"`
	ChanceOfPlayingThisRound int `json:"chance_of_playing_this_round"`
	CleanSheets int `json:"clean_sheets"`
	CleanSheetsPer90 string `json:"clean_sheets_per_90"`
	CornersAndIndirectFreekicksOrder int `json:"corners_and_indirect_freekicks_order"`
	CostChangeEvent int `json:"cost_change_event"`
	CostChangeEventFall int `json:"cost_change_event_fall"`
	CostChangeStart int `json:"cost_change_start"`
	CostChangeStartFall int `json:"cost_change_start_fall"`
	Creativity string `json:"creativity"`
	DirectFreekicksOrder int `json:"direct_freekicks_order"`
	DreamteamCount int `json:"dreamteam_count"`
	ElementType int `json:"element_type"`
	EpNext string `json:"ep_next"`
	EpThis string `json:"ep_this"`
	EventPoints int `json:"event_points"`
	ExpectedAssists string `json:"expected_assists"`
	ExpectedAssistsPer90 string `json:"expected_assists_per_90"`
	ExpectedGoalInvolvements string `json:"expected_goal_involvements"`
	ExpectedGoalInvolvementsPer90 string `json:"expected_goal_involvements_per_90"`
	ExpectedGoals string `json:"expected_goals"`
	ExpectedGoalsConceded string `json:"expected_goals_conceded"`
	ExpectedGoalsConcededPer90 string `json:"expected_goals_conceded_per_90"`
	ExpectedGoalsPer90 string `json:"expected_goals_per_90"`
	FirstName string `json:"first_name"`
	Form string `json:"form"`
	FormRank int `json:"form_rank"`
	GoalsConceded int `json:"goals_conceded"`
	GoalsConcededPer90 string `json:"goals_conceded_per_90"`
	GoalsScored int `json:"goals_scored"`
	IctIndex string `json:"ict_index"`
	IctIndexRank int `json:"ict_index_rank"`
	Id int `json:"id"`
	InDreamteam bool `json:"in_dreamteam"`
	Influence string `json:"influence"`
	Minutes int `json:"minutes"`
	News string `json:"news"`
	NewsAdded string `json:"news_added"`
	NowCost int `json:"now_cost"`
	NowCostRank int `json:"now_cost_rank"`
	OwnGoals int `json:"own_goals"`
	PenaltiesMissed int `json:"penalties_missed"`
	PenaltiesOrder int `json:"penalties_order"`
	PenaltiesSaved int `json:"penalties_saved"`
	Photo string `json:"photo"`
	PointsPerGame string `json:"points_per_game"`
	RedCards int `json:"red_cards"`
	Saves int `json:"saves"`
	SavesPer90 string `json:"saves_per_90"`
	SecondName string `json:"second_name"`
	SelectedByPercent string `json:"selected_by_percent"`
	SelectedRank int `json:"selected_rank"`
	Starts int `json:"starts"`
	StartsPer90 string `json:"starts_per_90"`
	Status string `json:"status"`
	Team int `json:"team"`
	TeamCode int `json:"team_code"`
	Threat string `json:"threat"`
	TotalPoints int `json:"total_points"`
	TransfersIn int `json:"transfers_in"`
	TransfersInEvent int `json:"transfers_in_event"`
	TransfersOut int `json:"transfers_out"`
	TransfersOutEvent int `json:"transfers_out_event"`
	ValueForm string `json:"value_form"`
	ValueSeason string `json:"value_season"`
	WebName string `json:"web_name"`
	YellowCards int `json:"yellow_cards"`
}

type ElementStat struct {
	Label string `json:"label"`
	Name string `json:"name"`
}

type ElementSummary struct {
	Fixtures json.RawMessage `json:"fixtures"`
	History json.RawMessage `json:"history"`
	HistoryPast json.RawMessage `json:"history_past"`
}

type ElementType struct {
	Id int `json:"id"`
	PluralName string `json:"plural_name"`
	PluralNameShort string `json:"plural_name_short"`
	SingularName string `json:"singular_name"`
	SingularNameShort string `json:"singular_name_short"`
	SquadMaxPlay int `json:"squad_max_play"`
	SquadMinPlay int `json:"squad_min_play"`
	SquadSelect int `json:"squad_select"`
}

type Entry struct {
	CurrentEvent int `json:"current_event"`
	FavouriteTeam int `json:"favourite_team"`
	Id int `json:"id"`
	JoinedTime string `json:"joined_time"`
	Kit string `json:"kit"`
	LastDeadlineBank int `json:"last_deadline_bank"`
	LastDeadlineValue int `json:"last_deadline_value"`
	Leagues json.RawMessage `json:"leagues"`
	Name string `json:"name"`
	PlayerFirstName string `json:"player_first_name"`
	PlayerLastName string `json:"player_last_name"`
	StartedEvent int `json:"started_event"`
	SummaryEventPoints int `json:"summary_event_points"`
	SummaryEventRank int `json:"summary_event_rank"`
	SummaryOverallPoints int `json:"summary_overall_points"`
	SummaryOverallRank int `json:"summary_overall_rank"`
}

type EntryEvent struct {
	ActiveChip string `json:"active_chip"`
	AutomaticSubs json.RawMessage `json:"automatic_subs"`
	EntryHistory json.RawMessage `json:"entry_history"`
	Picks json.RawMessage `json:"picks"`
}

type EntryEventHistory struct {
	Bank int `json:"bank"`
	Event int `json:"event"`
	EventTransfers int `json:"event_transfers"`
	EventTransfersCost int `json:"event_transfers_cost"`
	OverallRank int `json:"overall_rank"`
	Points int `json:"points"`
	PointsOnBench int `json:"points_on_bench"`
	Rank int `json:"rank"`
	RankSort int `json:"rank_sort"`
	TotalPoints int `json:"total_points"`
	Value int `json:"value"`
}

type EntryHistory struct {
	Chips json.RawMessage `json:"chips"`
	Current json.RawMessage `json:"current"`
	Past json.RawMessage `json:"past"`
}

type EntryLeagueInfo struct {
	EntryCanAdmin bool `json:"entry_can_admin"`
	EntryCanLeave bool `json:"entry_can_leave"`
	EntryLastRank int `json:"entry_last_rank"`
	EntryRank int `json:"entry_rank"`
	Id int `json:"id"`
	LeagueType string `json:"league_type"`
	Name string `json:"name"`
	ShortName string `json:"short_name"`
	StartEvent int `json:"start_event"`
}

type Event struct {
	AverageEntryScore int `json:"average_entry_score"`
	ChipPlays json.RawMessage `json:"chip_plays"`
	DataChecked bool `json:"data_checked"`
	DeadlineTime string `json:"deadline_time"`
	DeadlineTimeEpoch int `json:"deadline_time_epoch"`
	Finished bool `json:"finished"`
	HighestScore int `json:"highest_score"`
	HighestScoringEntry int `json:"highest_scoring_entry"`
	Id int `json:"id"`
	IsCurrent bool `json:"is_current"`
	IsNext bool `json:"is_next"`
	IsPrevious bool `json:"is_previous"`
	MostCaptained int `json:"most_captained"`
	MostSelected int `json:"most_selected"`
	MostTransferredIn int `json:"most_transferred_in"`
	MostViceCaptained int `json:"most_vice_captained"`
	Name string `json:"name"`
	TopElement int `json:"top_element"`
	TopElementInfo json.RawMessage `json:"top_element_info"`
	TransfersMade int `json:"transfers_made"`
}

type EventStatus struct {
	Leagues string `json:"leagues"`
	Status json.RawMessage `json:"status"`
}

type Fixture struct {
	Code int `json:"code"`
	Event int `json:"event"`
	Finished bool `json:"finished"`
	FinishedProvisional bool `json:"finished_provisional"`
	Id int `json:"id"`
	KickoffTime string `json:"kickoff_time"`
	Minutes int `json:"minutes"`
	Started bool `json:"started"`
	Stats json.RawMessage `json:"stats"`
	TeamA int `json:"team_a"`
	TeamADifficulty int `json:"team_a_difficulty"`
	TeamAScore int `json:"team_a_score"`
	TeamH int `json:"team_h"`
	TeamHDifficulty int `json:"team_h_difficulty"`
	TeamHScore int `json:"team_h_score"`
}

type GameSettings struct {
	LeagueJoinPrivateMax int `json:"league_join_private_max"`
	SquadSquadplay int `json:"squad_squadplay"`
	SquadSquadsize int `json:"squad_squadsize"`
	SquadTeamLimit int `json:"squad_team_limit"`
	SquadTotalSpend int `json:"squad_total_spend"`
	TransfersCap int `json:"transfers_cap"`
	TransfersSellOnFee float64 `json:"transfers_sell_on_fee"`
}

type H2HLeague struct {
	League json.RawMessage `json:"league"`
	NewEntries json.RawMessage `json:"new_entries"`
	Standings json.RawMessage `json:"standings"`
}

type H2HLeagueEntry struct {
	Entry int `json:"entry"`
	EntryName string `json:"entry_name"`
	Id int `json:"id"`
	LastRank int `json:"last_rank"`
	MatchesDrawn int `json:"matches_drawn"`
	MatchesLost int `json:"matches_lost"`
	MatchesPlayed int `json:"matches_played"`
	MatchesWon int `json:"matches_won"`
	PlayerName string `json:"player_name"`
	PointsFor int `json:"points_for"`
	Rank int `json:"rank"`
	RankSort int `json:"rank_sort"`
	Total int `json:"total"`
}

type H2HLeagueMatches struct {
	HasNext bool `json:"has_next"`
	Page int `json:"page"`
	Results json.RawMessage `json:"results"`
}

type H2HMatch struct {
	Entry1Draw int `json:"entry_1_draw"`
	Entry1Entry int `json:"entry_1_entry"`
	Entry1Loss int `json:"entry_1_loss"`
	Entry1Name string `json:"entry_1_name"`
	Entry1PlayerName string `json:"entry_1_player_name"`
	Entry1Points int `json:"entry_1_points"`
	Entry1Total int `json:"entry_1_total"`
	Entry1Win int `json:"entry_1_win"`
	Entry2Draw int `json:"entry_2_draw"`
	Entry2Entry int `json:"entry_2_entry"`
	Entry2Loss int `json:"entry_2_loss"`
	Entry2Name string `json:"entry_2_name"`
	Entry2PlayerName string `json:"entry_2_player_name"`
	Entry2Points int `json:"entry_2_points"`
	Entry2Total int `json:"entry_2_total"`
	Entry2Win int `json:"entry_2_win"`
	Event int `json:"event"`
	Id int `json:"id"`
	IsKnockout bool `json:"is_knockout"`
	Winner int `json:"winner"`
}

type HistoryEntry struct {
	Assists int `json:"assists"`
	Bonus int `json:"bonus"`
	Bps int `json:"bps"`
	CleanSheets int `json:"clean_sheets"`
	Creativity string `json:"creativity"`
	Element int `json:"element"`
	Fixture int `json:"fixture"`
	GoalsConceded int `json:"goals_conceded"`
	GoalsScored int `json:"goals_scored"`
	IctIndex string `json:"ict_index"`
	Influence string `json:"influence"`
	KickoffTime string `json:"kickoff_time"`
	Minutes int `json:"minutes"`
	OpponentTeam int `json:"opponent_team"`
	OwnGoals int `json:"own_goals"`
	PenaltiesMissed int `json:"penalties_missed"`
	PenaltiesSaved int `json:"penalties_saved"`
	RedCards int `json:"red_cards"`
	Round int `json:"round"`
	Saves int `json:"saves"`
	Selected int `json:"selected"`
	TeamAScore int `json:"team_a_score"`
	TeamHScore int `json:"team_h_score"`
	Threat string `json:"threat"`
	TotalPoints int `json:"total_points"`
	TransfersBalance int `json:"transfers_balance"`
	TransfersIn int `json:"transfers_in"`
	TransfersOut int `json:"transfers_out"`
	Value int `json:"value"`
	WasHome bool `json:"was_home"`
	YellowCards int `json:"yellow_cards"`
}

type LeagueInfo struct {
	AdminEntry int `json:"admin_entry"`
	Closed bool `json:"closed"`
	Created string `json:"created"`
	Id int `json:"id"`
	LeagueType string `json:"league_type"`
	MaxEntries int `json:"max_entries"`
	Name string `json:"name"`
	StartEvent int `json:"start_event"`
}

type LiveData struct {
	Elements json.RawMessage `json:"elements"`
}

type LiveElement struct {
	Explain json.RawMessage `json:"explain"`
	Id int `json:"id"`
	Stats json.RawMessage `json:"stats"`
}

type LiveStats struct {
	Assists int `json:"assists"`
	Bonus int `json:"bonus"`
	Bps int `json:"bps"`
	CleanSheets int `json:"clean_sheets"`
	GoalsConceded int `json:"goals_conceded"`
	GoalsScored int `json:"goals_scored"`
	InDreamteam bool `json:"in_dreamteam"`
	Minutes int `json:"minutes"`
	OwnGoals int `json:"own_goals"`
	PenaltiesMissed int `json:"penalties_missed"`
	PenaltiesSaved int `json:"penalties_saved"`
	RedCards int `json:"red_cards"`
	Saves int `json:"saves"`
	TotalPoints int `json:"total_points"`
	YellowCards int `json:"yellow_cards"`
}

type PastSeasonHistory struct {
	Assists int `json:"assists"`
	Bonus int `json:"bonus"`
	Bps int `json:"bps"`
	CleanSheets int `json:"clean_sheets"`
	Creativity string `json:"creativity"`
	ElementCode int `json:"element_code"`
	EndCost int `json:"end_cost"`
	GoalsConceded int `json:"goals_conceded"`
	GoalsScored int `json:"goals_scored"`
	IctIndex string `json:"ict_index"`
	Influence string `json:"influence"`
	Minutes int `json:"minutes"`
	OwnGoals int `json:"own_goals"`
	PenaltiesMissed int `json:"penalties_missed"`
	PenaltiesSaved int `json:"penalties_saved"`
	RedCards int `json:"red_cards"`
	Saves int `json:"saves"`
	SeasonName string `json:"season_name"`
	StartCost int `json:"start_cost"`
	Threat string `json:"threat"`
	TotalPoints int `json:"total_points"`
	YellowCards int `json:"yellow_cards"`
}

type Pick struct {
	Element int `json:"element"`
	IsCaptain bool `json:"is_captain"`
	IsViceCaptain bool `json:"is_vice_captain"`
	Multiplier int `json:"multiplier"`
	Position int `json:"position"`
}

type Team struct {
	Code int `json:"code"`
	Draw int `json:"draw"`
	Form string `json:"form"`
	Id int `json:"id"`
	Loss int `json:"loss"`
	Name string `json:"name"`
	Played int `json:"played"`
	Points int `json:"points"`
	Position int `json:"position"`
	ShortName string `json:"short_name"`
	Strength int `json:"strength"`
	StrengthAttackAway int `json:"strength_attack_away"`
	StrengthAttackHome int `json:"strength_attack_home"`
	StrengthDefenceAway int `json:"strength_defence_away"`
	StrengthDefenceHome int `json:"strength_defence_home"`
	StrengthOverallAway int `json:"strength_overall_away"`
	StrengthOverallHome int `json:"strength_overall_home"`
	Unavailable bool `json:"unavailable"`
	Win int `json:"win"`
}

type Transfer struct {
	ElementIn int `json:"element_in"`
	ElementInCost int `json:"element_in_cost"`
	ElementOut int `json:"element_out"`
	ElementOutCost int `json:"element_out_cost"`
	Entry int `json:"entry"`
	Event int `json:"event"`
	Time string `json:"time"`
}

type UpcomingFixture struct {
	Code int `json:"code"`
	Difficulty int `json:"difficulty"`
	Event int `json:"event"`
	Finished bool `json:"finished"`
	Id int `json:"id"`
	IsHome bool `json:"is_home"`
	KickoffTime string `json:"kickoff_time"`
	Minutes int `json:"minutes"`
	TeamA int `json:"team_a"`
	TeamAScore int `json:"team_a_score"`
	TeamH int `json:"team_h"`
	TeamHScore int `json:"team_h_score"`
}
