// Copyright 2026 mbulling83. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/mbulling83/fpl-pp-cli/internal/cli"
	"github.com/mbulling83/fpl-pp-cli/internal/client"
	"github.com/mbulling83/fpl-pp-cli/internal/config"
	"github.com/mbulling83/fpl-pp-cli/internal/mcp/cobratree"
	"github.com/mbulling83/fpl-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("bootstrap-static_get-bootstrap",
			mcplib.WithDescription("The main data endpoint. Returns all players (800+), teams (20), gameweeks (38), game settings, and element types. This is the primary data source for the local SQLite store."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/bootstrap-static/", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("dream-team_get",
			mcplib.WithDescription("The best XI of the entire season by total points scored. Returns the DreamTeam."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/dream-team/", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("element-summary_get-player-summary",
			mcplib.WithDescription("Per-player game-by-game stats, upcoming fixtures with difficulty ratings, and multi-season history. Required: elementId. Returns the ElementSummary."),
			mcplib.WithString("elementId", mcplib.Required(), mcplib.Description("Player ID from bootstrap elements array")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/element-summary/{elementId}/", []mcpParamBinding{{PublicName: "elementId", WireName: "elementId", Location: "path"}, }, []string{"elementId", }),
	)
	s.AddTool(
		mcplib.NewTool("entry_get",
			mcplib.WithDescription("Manager profile including team name, overall rank, points, and league memberships. Required: entryId. Returns the Entry."),
			mcplib.WithString("entryId", mcplib.Required(), mcplib.Description("Manager entry ID (visible in the FPL URL after /entry/)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{entryId}/", []mcpParamBinding{{PublicName: "entryId", WireName: "entryId", Location: "path"}, }, []string{"entryId", }),
	)
	s.AddTool(
		mcplib.NewTool("entry_event_get-entry-picks",
			mcplib.WithDescription("Which players were selected, who was captained, vice-captain, and any chip played for a specific gameweek. Required: entryId, eventId. Returns the EntryEvent."),
			mcplib.WithString("entryId", mcplib.Required(), mcplib.Description("Manager entry ID")),
			mcplib.WithString("eventId", mcplib.Required(), mcplib.Description("Gameweek ID (1-38)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{entryId}/event/{eventId}/picks/", []mcpParamBinding{{PublicName: "entryId", WireName: "entryId", Location: "path"},{PublicName: "eventId", WireName: "eventId", Location: "path"}, }, []string{"entryId","eventId", }),
	)
	s.AddTool(
		mcplib.NewTool("entry_history_get-entry",
			mcplib.WithDescription("Full gameweek-by-gameweek history for a manager including points, rank, bank balance, team value, and chips played. Also includes past season summaries. Required: entryId. Returns the EntryHistory."),
			mcplib.WithString("entryId", mcplib.Required(), mcplib.Description("Manager entry ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{entryId}/history/", []mcpParamBinding{{PublicName: "entryId", WireName: "entryId", Location: "path"}, }, []string{"entryId", }),
	)
	s.AddTool(
		mcplib.NewTool("entry_transfers_get-entry",
			mcplib.WithDescription("All transfers made by a manager this season including player bought/sold, prices, and gameweek timing. Required: entryId. Returns array of Transfer."),
			mcplib.WithString("entryId", mcplib.Required(), mcplib.Description("Manager entry ID")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/entry/{entryId}/transfers/", []mcpParamBinding{{PublicName: "entryId", WireName: "entryId", Location: "path"}, }, []string{"entryId", }),
	)
	s.AddTool(
		mcplib.NewTool("event_live_get-gameweek",
			mcplib.WithDescription("Real-time player points, stats, and bonus points for a gameweek. Updated during matches. Required: eventId. Returns the LiveData."),
			mcplib.WithString("eventId", mcplib.Required(), mcplib.Description("Gameweek ID (1-38)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/event/{eventId}/live/", []mcpParamBinding{{PublicName: "eventId", WireName: "eventId", Location: "path"}, }, []string{"eventId", }),
	)
	s.AddTool(
		mcplib.NewTool("event-status_get",
			mcplib.WithDescription("Status of bonus points processing and league updates for recent match days. Returns the EventStatus."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/event-status/", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("fixtures_list",
			mcplib.WithDescription("All Premier League fixtures for the season, or filtered to a specific gameweek. Optional: event, future. Returns array of Fixture."),
			mcplib.WithString("event", mcplib.Description("Filter to a specific gameweek (1-38)")),
			mcplib.WithString("future", mcplib.Description("Set to 1 to return only future fixtures")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/fixtures/", []mcpParamBinding{{PublicName: "event", WireName: "event", Location: "query"},{PublicName: "future", WireName: "future", Location: "query"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("leagues-classic_standings_get-classic-league",
			mcplib.WithDescription("Standings for a classic (points-based) mini-league. Paginated. Required: leagueId. Optional: page_standings (default: 1), page_new_entries (default: 1), phase (default: 1). Returns the ClassicLeague."),
			mcplib.WithString("leagueId", mcplib.Required(), mcplib.Description("Classic league ID")),
			mcplib.WithString("page_standings", mcplib.Description("Page number for standings")),
			mcplib.WithString("page_new_entries", mcplib.Description("Page number for new entries")),
			mcplib.WithString("phase", mcplib.Description("Phase ID (1 = overall)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/leagues-classic/{leagueId}/standings/", []mcpParamBinding{{PublicName: "leagueId", WireName: "leagueId", Location: "path"},{PublicName: "page_standings", WireName: "page_standings", Location: "query"},{PublicName: "page_new_entries", WireName: "page_new_entries", Location: "query"},{PublicName: "phase", WireName: "phase", Location: "query"}, }, []string{"leagueId", }),
	)
	s.AddTool(
		mcplib.NewTool("leagues-h2h_standings_get-h2-hleague",
			mcplib.WithDescription("Standings for a head-to-head league with win/draw/loss records. Required: leagueId. Optional: page_standings (default: 1), page_new_entries (default: 1). Returns the H2Hleague."),
			mcplib.WithString("leagueId", mcplib.Required(), mcplib.Description("H2H league ID")),
			mcplib.WithString("page_standings", mcplib.Description("Page number for standings")),
			mcplib.WithString("page_new_entries", mcplib.Description("Page number for new entries")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/leagues-h2h/{leagueId}/standings/", []mcpParamBinding{{PublicName: "leagueId", WireName: "leagueId", Location: "path"},{PublicName: "page_standings", WireName: "page_standings", Location: "query"},{PublicName: "page_new_entries", WireName: "page_new_entries", Location: "query"}, }, []string{"leagueId", }),
	)
	s.AddTool(
		mcplib.NewTool("leagues-h2h-matches_list-h2-hmatches",
			mcplib.WithDescription("All head-to-head match results for a specific entry in an H2H league. Required: leagueId. Optional: entry, page (default: 1). Returns the H2HleagueMatches."),
			mcplib.WithString("leagueId", mcplib.Required(), mcplib.Description("H2H league ID")),
			mcplib.WithString("entry", mcplib.Description("Filter to a specific entry ID's matches")),
			mcplib.WithString("page", mcplib.Description("Page number")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/leagues-h2h-matches/league/{leagueId}/", []mcpParamBinding{{PublicName: "leagueId", WireName: "leagueId", Location: "path"},{PublicName: "entry", WireName: "entry", Location: "query"},{PublicName: "page", WireName: "page", Location: "query"}, }, []string{"leagueId", }),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'fpl-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'fpl-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "fpl-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "fpl-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "fpl",
		"description": "Every FPL feature, plus offline queries, cross-gameweek analysis, and a local database no other FPL tool has.",
		"archetype":   "payments",
		"tool_count":  13,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion fpl-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name": "bootstrap-static",
				"description": "Manage bootstrap static",
				"endpoints": []string{"get-bootstrap",  },
				"syncable": true,
			},
			{
				"name": "dream-team",
				"description": "Manage dream team",
				"endpoints": []string{"get",  },
			},
			{
				"name": "element-summary",
				"description": "Manage element summary",
				"endpoints": []string{"get-player-summary",  },
			},
			{
				"name": "entry",
				"description": "Manage entry",
				"endpoints": []string{"get",  },
			},
			{
				"name": "event",
				"description": "Gameweek events and live data",
				"endpoints": []string{ },
			},
			{
				"name": "event-status",
				"description": "Manage event status",
				"endpoints": []string{"get",  },
			},
			{
				"name": "fixtures",
				"description": "Match fixtures and results",
				"endpoints": []string{"list",  },
				"syncable": true,
			},
			{
				"name": "leagues-classic",
				"description": "Manage leagues classic",
				"endpoints": []string{ },
			},
			{
				"name": "leagues-h2h",
				"description": "Manage leagues h2h",
				"endpoints": []string{ },
			},
			{
				"name": "leagues-h2h-matches",
				"description": "Manage leagues h2h matches",
				"endpoints": []string{"list-h2-hmatches",  },
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Financial data", "insight": "Always use read-only operations for financial queries. Never use create/update tools for payment data without explicit user confirmation."},
			{"topic": "Reconciliation", "insight": "For reconciliation tasks, sync first then use sql for cross-referencing. API pagination over financial records is slow and rate-limited."},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
