// Copyright 2026 mbulling83. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEntryEventCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "event",
		Short: "Gameweek events and live data",
	}

	cmd.AddCommand(newEntryEventGetEntryPicksCmd(flags))
	return cmd
}
