// Copyright 2026 mbulling83. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLeaguesClassicCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "leagues-classic",
		Short: "Manage leagues classic",
	}

	cmd.AddCommand(newLeaguesClassicStandingsCmd(flags))
	return cmd
}
