// Copyright 2026 mbulling83. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLeaguesH2hStandingsGetH2HleagueCmd(flags *rootFlags) *cobra.Command {
	var flagPageStandings int
	var flagPageNewEntries int

	cmd := &cobra.Command{
		Use:   "get-h2-hleague <leagueId>",
		Aliases: []string{"get"},
		Short: "Standings for a head-to-head league with win/draw/loss records.",
		Example: "  fpl-pp-cli leagues-h2h standings get-h2-hleague 42",
		Annotations: map[string]string{"pp:endpoint": "standings.get-h2-hleague", "pp:method": "GET", "pp:path": "/leagues-h2h/{leagueId}/standings/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/leagues-h2h/{leagueId}/standings/"
			path = replacePathParam(path, "leagueId", args[0])
			params := map[string]string{}
			if flagPageStandings != 0 {
				params["page_standings"] = fmt.Sprintf("%v", flagPageStandings)
			}
			if flagPageNewEntries != 0 {
				params["page_new_entries"] = fmt.Sprintf("%v", flagPageNewEntries)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "standings", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagPageStandings, "page-standings", 1, "Page number for standings")
	cmd.Flags().IntVar(&flagPageNewEntries, "page-new-entries", 1, "Page number for new entries")

	return cmd
}
