// Copyright 2026 mbulling83. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFixturesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagEvent int
	var flagFuture int

	cmd := &cobra.Command{
		Use:   "fixtures",
		Short: "All Premier League fixtures for the season, or filtered to a specific gameweek.",
		Long:  "Shortcut for 'fixtures list'. All Premier League fixtures for the season, or filtered to a specific gameweek.",
		Example: "  fpl-pp-cli fixtures",
		Annotations: map[string]string{"pp:endpoint": "fixtures.list", "pp:method": "GET", "pp:path": "/fixtures/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/fixtures/"
			params := map[string]string{}
			if flagEvent != 0 {
				params["event"] = fmt.Sprintf("%v", flagEvent)
			}
			if flagFuture != 0 {
				params["future"] = fmt.Sprintf("%v", flagFuture)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "fixtures", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagEvent, "event", 0, "Filter to a specific gameweek (1-38)")
	cmd.Flags().IntVar(&flagFuture, "future", 0, "Set to 1 to return only future fixtures (one of: 0, 1)")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
