// Copyright 2026 mbulling83. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newLeaguesH2hMatchesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagEntry int
	var flagPage string

	cmd := &cobra.Command{
		Use:   "leagues-h2h-matches <leagueId>",
		Short: "All head-to-head match results for a specific entry in an H2H league.",
		Long:  "Shortcut for 'leagues-h2h-matches list-h2-hmatches'. All head-to-head match results for a specific entry in an H2H league.",
		Example: "  fpl-pp-cli leagues-h2h-matches 42",
		Annotations: map[string]string{"pp:endpoint": "leagues-h2h-matches.list-h2-hmatches", "pp:method": "GET", "pp:path": "/leagues-h2h-matches/league/{leagueId}/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/leagues-h2h-matches/league/{leagueId}/"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "leagueId is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "leagueId"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("leagueId is required\nUsage: %s <%s>", cmd.CommandPath(), "leagueId"))
			}
			path = replacePathParam(path, "leagueId", args[0])
			params := map[string]string{}
			if flagEntry != 0 {
				params["entry"] = fmt.Sprintf("%v", flagEntry)
			}
			if flagPage != "" {
				params["page"] = fmt.Sprintf("%v", flagPage)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "leagues-h2h-matches", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagEntry, "entry", 0, "Filter to a specific entry ID's matches")
	cmd.Flags().StringVar(&flagPage, "page", "1", "Page number")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
